config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :despachos
  resources :armas
  resources :guardas
  resources :equipes
  resources :unidades
  devise_for :users
end

app/models/unidade.rb
class Unidade < ApplicationRecord
  validates :nome, presence: true  
  has_many :equipes, dependent: :destroy
  end
  

app/controllers/unidades_controller.rb
class UnidadesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_unidade, only: %i[ show edit update destroy ]

  # GET /unidades or /unidades.json
  def index
    @unidades = Unidade.all
  end

  # GET /unidades/1 or /unidades/1.json
  def show
  end

  # GET /unidades/new
  def new
    @unidade = Unidade.new
  end

  # GET /unidades/1/edit
  def edit
  end

  # POST /unidades or /unidades.json
  def create
    @unidade = Unidade.new(unidade_params)

    respond_to do |format|
      if @unidade.save
        format.html { redirect_to @unidade, notice: "Unidade criada." }
        format.json { render :show, status: :created, location: @unidade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unidades/1 or /unidades/1.json
  def update
    respond_to do |format|
      if @unidade.update(unidade_params)
        format.html { redirect_to @unidade, notice: "Unidade atualizada." }
        format.json { render :show, status: :ok, location: @unidade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unidades/1 or /unidades/1.json
  def destroy
    @unidade.destroy!

    respond_to do |format|
      format.html { redirect_to unidades_path, status: :see_other, notice: "Unidade excluída." }
      format.json { head :no_content }
    end
  end

  private
    def set_unidade
      @unidade = Unidade.find(params.expect(:id))
    end

    def unidade_params
      params.expect(unidade: [ :nome ])
    end
end

app/helpers/unidades_helper.rb
module UnidadesHelper
end

app/views/unidades/_form.html.erb
<%= form_with(model: unidade) do |form| %>
  <% if unidade.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(unidade.errors.count, "error") %> impediram essa unidade de ser criada:</h2>

      <ul>
        <% unidade.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block", class: "field-text" %>
    <%= form.text_field :nome, class: "input-centralizado" %>
  </div>

  <div class="actions">
    <%= form.submit "Cadastrar Unidade", class: "button" %>
  </div>
<% end %>

app/views/unidades/_unidade.html.erb
<div id="<%= dom_id unidade %>" class="show-card">
  <h3 class="unit-name"><%= unidade.nome %></h3>
  
  <div class="card-actions">
    <%= link_to "Visualizar Unidade", unidade, class: "button card-button" %>
  </div>
</div>

app/views/unidades/edit.html.erb
<% content_for :title, "Editar unidade" %>

<div class="form-container">
  <h1 class="show-titulo">Editar unidade</h1>

  <%= render "form", unidade: @unidade %>
  
  <div class="form-links">
    <%= link_to "Mostrar unidade", @unidade, class: "button" %>
    <%= link_to "Voltar", unidades_path, class: "button" %>
  </div>
</div>

app/views/unidades/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Unidades" %>

<h1 class="show-titulo">Unidades</h1>

<div id="unidades">
  <% @unidades.each do |unidade| %>
    <%= render unidade %>
  <% end %>
</div>

<div class="mt-4">
  <%= link_to "Nova Unidade", new_unidade_path, class: "button2" %>
</div>

app/views/unidades/new.html.erb
<% content_for :title, "Nova unidade" %>

<div class="form-container">
  <h1 class="show-titulo">Nova unidade</h1>

  <%= render "form", unidade: @unidade %>
  
  <div class="form-links">
    <%= link_to "Voltar", unidades_path, class: "button" %>
  </div>
</div>

app/views/unidades/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @unidade %>

<div>
  <%= link_to "Editar unidade", edit_unidade_path(@unidade), class: "button" %> |
  <%= link_to "Unidades", unidades_path, class: "button" %>
</div>

<div>
   <%= button_to "Excluir essa unidade", @unidade, method: :delete, class: "button3" %>
</div>